version: "3.3"
services:
  traefik:
    image: eherbert/traefik
    command: --docker  --docker.swarmmode --api --docker.domain=edward-of-clt.com --docker.watch --logLevel=DEBUG
    networks:
      - traefik
    ports:
      - 80:80
#      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik.toml:/traefik.toml
      - /dev/null:/acme.json
    deploy:
      placement:
        constraints: [node.role==manager]
        
networks:
  traefik:
    external: true
