[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "abeh78@gmail.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.edward-of-clt.com"
[[acme.domains]]
  main = "*.kainoscharlotte.com"
