[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "abeh78@gmail.com"
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.edward-of-clt.com"
  sans = ["edward-of-clt.com"]
[[acme.domains]]
  main = "*.reconcilecharlotte.com"
  sans = ["reconcilecharlotte.com"]
